<?php 

	$img = array(
	    'ID' => '760',
	    'id' => '760',
	    'title' => '',
	    'filename' => 'featured-image.jpg',
	    'filesize' => '597371',
	    'url' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	    'alt' => '',
	    'author' => '3',
	    'description' => '',
	    'caption' => '',
	    'name' => 'about-us',
	    'status' => 'inherit',
	    'uploaded_to' => '19',
	    'date' => '2018-11-06 09:30:40',
	    'modified' => '2018-11-06 09:31:21',
	    'menu_order' => '0',
	    'mime_type' => 'image/jpeg',
	    'type' => 'image',
	    'subtype' => 'jpeg',
	    'icon' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	    'width' => '1080',
	    'height' => '800',
	    'sizes' => array(
	        'thumbnail' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'thumbnail-width' => '150',
	        'thumbnail-height' => '150',
	        'medium' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'medium-width' => '300',
	        'medium-height' => '175',
	        'medium_large' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'medium_large-width' => '768',
	        'medium_large-height' => '448',
	        'large' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'large-width' => '1024',
	        'large-height' => '597',
	        'featured-small' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'featured-small-width' => '640',
	        'featured-small-height' => '200',
	        'featured-medium' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'featured-medium-width' => '1080',
	        'featured-medium-height' => '400',
	        'featured-large' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'featured-large-width' => '1080',
	        'featured-large-height' => '400',
	        'featured-xlarge' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'featured-xlarge-width' => '1080',
	        'featured-xlarge-height' => '400',
	        'fp-small' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'fp-small-width' => '640',
	        'fp-small-height' => '373',
	        'fp-medium' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'fp-medium-width' => '1024',
	        'fp-medium-height' => '597',
	        'fp-large' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'fp-large-width' => '1080',
	        'fp-large-height' => '630',
	        'fp-xlarge' => get_template_directory_uri() . '/src/images/example/4891.jpg',
	        'fp-xlarge-width' => '1080',
	        'fp-xlarge-height' => '630'
	    	)
	);

?>